### PR TITLE
Con 4085 new field in availability block

### PR DESCRIPTION
**Pull request by glendoci**
**Release note**
https://mews.atlassian.net/browse/CON-4085: Added ability to send the flag back so they know if the availability block is All In One Group, or Individual Groups

**Summary**
Added ability to send the flag back so they know if the availability block is All In One Group, or Individual Groups updated documentation to show this new field

### CODE REVIEW

**Review by MikeAdamsMews — COMMENTED** [review]
Hi @glendoci, I think the definition of `pickupType` is missing, i.e. the string enumeration.

**Comment by glendoci** [comment]
> Hi @glendoci, I think the definition of `pickupType` is missing, i.e. the string enumeration.

Sorry just added it in thank you!

**Review by MikeAdamsMews — APPROVED** [review]
Please set the Changelog date to the date of actual publication, when you are ready to merge. Thank you.

**Comment by glendoci** [comment]
> Please set the Changelog date to the date of actual publication, when you are ready to merge. Thank you.

Just changed the change log date to today's date @MikeAdamsMews

**Comment by glendoci** [comment]
@MikeAdamsMews  or anyone else could you guys merge it I am new and don't have permissions to do so unfortunately

**Review by patrikmiksovsky95 — APPROVED** [review]

**Pull request merged**
